spring.application.name=url-shortener
server.port=${PORT:8081}

app.base-url=${BASE_URL:http://localhost:8081}

spring.datasource.url=jdbc:h2:mem:urlshortener
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false